//chat
export const UPDATE_LAST_MESSAGE = "UPDATE_LAST_MESSAGE";
export const UPDATE_STATUS_CONVERSATION = "UPDATE_STATUS_CONVERSATION";
export const SET_STATUS_CONVERSATION = "SET_STATUS_CONVERSATION";
export const SET_CHAT = "SET_CHAT";
export const SET_LIST_CONVERSATION = "SET_LIST_CONVERSATION";
export const ADD_STATUS_CONVERSATION = "ADD_STATUS_CONVERSATION";
export const SET_CONVERSATION_CHAT = "SET_CONVERSATION_CHAT";
export const SET_IS_SHOW = "SET_IS_SHOW";
export const DISPLAY_CONVERSATION_ACCEPTS = "DISPLAY_CONVERSATION_ACCEPTS";
export const UPDATE_CONVERSATION_DISPLAYS = "UPDATE_CONVERSATION_DISPLAYS";
export const UPDATE_FRIEND_CHAT = "UPDATE_FRIEND_CHAT";

export const ADD_CONVERSATION_ACCEPTS = "ADD_CONVERSATION_ACCEPTS";
export const ADD_CONVERSATION_PENDINGS = "ADD_CONVERSATION_PENDINGS";
export const ADD_CONVERSATION = "ADD_CONVERSATION";

export const SET_NUMBER_UNREAD = "SET_NUMBER_UNREAD";
export const INCREASE_NUMBER_UNREAD = "INCREASE_NUMBER_UNREAD";
export const DECREASE_NUMBER_UNREAD = "DECREASE_NUMBER_UNREAD";

export const UPDATE_READ_CONVERSATION = "UPDATE_READ_CONVERSATION";
export const SET_NEW_CONVERSATION_CHAT = "SET_NEW_CONVERSATION_CHAT";
