export const SET_CREATE_ROOM = "SET_CREATE_ROOM";
export const ADD_FRIEND_TO_ROOM = "ADD_FRIEND_TO_ROOM";
export const REMOVE_FRIEND_TO_ROOM = "REMOVE_FRIEND_TO_ROOM";
export const SET_LIST_FRIEND = "SET_LIST_FRIEND";
export const RESET_CREATE_ROOM = "RESET_CREATE_ROOM";
