//Friend Request
export const SET_TYPE = "SET_TYPE";
export const SET_LIST_FRIEND_REQUEST = "SET_LIST_FRIEND_REQUEST";
export const ADD_LIST_FRIEND_REQUEST = "ADD_LIST_FRIEND_REQUEST";
export const REMOVE_FRIEND_REQUEST = "REMOVE_FRIEND_REQUEST";
export const INCREASE_NUMBER_FRIEND_REQUEST = "INCREASE_NUMBER_FRIEND_REQUEST";
export const SET_NUMBER_FRIEND_REQUEST = "SET_NUMBER_FRIEND_REQUEST";
