//chat
export const SET_LIST_NOTIFICATION = "SET_LIST_NOTIFICATION";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const SET_NUMBER_NOTIFICATION_UNREAD = "SET_NUMBER_NOTIFICATION_UNREAD";
export const INCREASE_NUMBER_NOTIFICATION_UNREAD =
  "INCREASE_NUMBER_NOTIFICATION_UNREAD";
export const DECREASE_NUMBER_NOTIFICATION_UNREAD =
  "DECREASE_NUMBER_NOTIFICATION_UNREAD";
export const SET_SHOW_NOTIFICATION = "SET_SHOW_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";
export const SET_TYPE_NOTIFICATION = "SET_TYPE_NOTIFICATION";
export const SET_NOTIFICATIONs_DISPLAY = "SET_NOTIFICATIONs_DISPLAY";
export const REMOVE_ALL_NOTIFICATION = "REMOVE_ALL_NOTIFICATION";
export const UPDATE_LIST_CONVERSATION = "UPDATE_LIST_CONVERSATION";
export const ADD_NOTIFICATION_DISPLAY = "ADD_NOTIFICATION_DISPLAY";
export const SET_SHOW_NOTIFICATION_MENU = "SET_SHOW_NOTIFICATION_MENU";
